### ISSUE TITLE
Link of data cannot be opened

### ISSUE THREAD

**Issue by su-hui-zz** [MengyuanChen21/ECCV2022-DELU#3]
I really want to know the algorithmic details of the article, but the data link given cannot be opened。 Could you give me another link such as baidu link or others?

**Comment by MengyuanChen21** [comment]
Thank you for the reminder! I have just uploaded the THUMOS14 dataset to both Google drive and Baidu disk.

Google drive link: https://drive.google.com/file/d/1SFEsQNLsG8vgBbqx056L9fjA4TzVZQEu/view?usp=sharing

Baidu disk: https://pan.baidu.com/s/1nspCSpzgwh5AHpSBPPibrQ?pwd=2dej 

Please contact me if you have any further problem!

**Comment by su-hui-zz** [comment]
Thanks so much!!!
