### ISSUE TITLE
Running code with activitynet 1.2

### ISSUE THREAD

**Issue by eeehco** [MengyuanChen21/ECCV2022-DELU#6]
Hello author, first of all, thank you for your excellent work!
I wanted to replicate the code using Activitynet 1.2, but found that there was no corresponding .sh code file. So I copied the THMOS14 running file and wrote an Activitynet 1.2 file, but encountered many problems. Is it correct to run the Activitynet dataset like this

**Comment by MengyuanChen21** [comment]
Thank you so much for the attention to our work!
The corresponding .sh code files for ActivityNet-v1.2 can be found in the folder "scripts" :)

**Comment by MengyuanChen21** [comment]
Note that the codes have been updated two weeks ago, including the model file and the .sh files for Act-v1.2. You can have a look at the updated files!

**Comment by eeehco** [comment]
Okay, I see it!Thank you

**Comment by eeehco** [comment]
But in train_ In activitynet.sh, the -- use model is ANT_ CO2, is this correct? An error was reported during operation

**Comment by MengyuanChen21** [comment]
Oh, sorry for the mistake. I have just corrected it. Are the codes running smoothly now?

**Comment by eeehco** [comment]
Yes, the code can now run, thank you
