### ISSUE TITLE
Is there a mapping file from split name to UCF-101 name?

### ISSUE THREAD

**Issue by Randle-Github** [MengyuanChen21/ECCV2022-DELU#8]
Thanks for your great work! I wonder if there exists a mapping file from the video name here like "video_test_0001098" to the real UCF-101 dataset video name?

**Comment by MengyuanChen21** [comment]
I guess there should be such a mapping file, since THUMOS-14 for WTAL is only a small subset of UCF101 . However, I am not very familiar with the whole UCF-101 dataset. You may need to seek help from contributors of THUMOS-14.
